### ISSUE TITLE
adding pictures to Multiscroll

### ISSUE THREAD

**Issue by knarfoe** [alvarotrigo/multiscroll.js#29]
Hello,
What's the best way to add images to Right1-3?
Is it wise to user Backstetch (from srobin on github)?

tnx
frank

**Comment by alvarotrigo** [comment]
As you can see in [the demo page](http://alvarotrigo.com/multiScroll/), just using background images is a way way to do it:

```css
.ms-right .section2 {
    background-image: url(imgs/tiger.jpg);
    background-repeat: no-repeat;
    background-position: right;
    background-size: auto 100%;
}
```
